Python NumPy is a general-purpose array processing package which provides tools for handling the n-dimensional arrays. It provides various computing tools such as comprehensive mathematical functions, linear algebra routines. NumPy provides both the flexibility of Python and the speed of well-optimized compiled C code. It’s easy to use syntax makes it highly accessible and productive for programmers from any background.

In [2]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [3]:
import numpy as np 

In [4]:
arr = np.array(my_list)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
matrix = [[1,2,3], [4,5,6],[7,8,9]]
arr_2d = np.array(matrix)
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.ones(4)

array([1., 1., 1., 1.])

In [10]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.random.randn(5)

array([-2.17954848, -1.12361145,  0.78754361, -0.75089112,  0.25675092])

In [13]:
np.random.randint(1,20,15)

array([16, 11,  9,  5,  3, 15, 14,  3,  6,  1,  8,  3, 18,  4,  2])

In [14]:
arr.dtype

dtype('int32')

In [16]:
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [17]:
arr[8]

8

In [18]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [21]:
arr[0:5] = 100
print(arr)

[100 100 100 100 100   5   6   7   8   9  10]


In [22]:
matrix = [[1,2,3], [4,5,6],[7,8,9]]
arr_2d = np.array(matrix)
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
arr_2d[0][2]

3

In [24]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [30]:
arr_2d[0,1]

2

In [25]:
print(arr)

[100 100 100 100 100   5   6   7   8   9  10]


In [26]:
arr + arr

array([200, 200, 200, 200, 200,  10,  12,  14,  16,  18,  20])

In [27]:
arr + 100

array([200, 200, 200, 200, 200, 105, 106, 107, 108, 109, 110])